- label: 上腹部
  values: &1
  - 阴
  - 阳
  - 表
  - 里
  - 虚
  - 实
  - 寒
  - 热
- label: 中腹部
  values: *1
- label: 下腹部
  values: *1
- label: 左腹部
  values: *1
- label: 右腹部
  values: *1
- label: 左上腹部
  values: *1
- label: 左下腹部
  values: *1
- label: 右上腹部
  values: *1
- label: 右下腹部
  values: *1
