- label: 中一两额动脉（太阳）
  values: []
- label: 中一两侧耳前动脉（耳门）
  values: []
- label: 下一两额动脉（地仓，大迎）
  values: []
- label: 上一手太阴肺经动脉（寸口）
  values: []
- label: 中一手少阴心经动脉（神门）
  values: []
- label: 下一手阳明大肠动脉（合谷）
  values: []
- label: 上一足厥阴肝经动脉（五里）
  values: []
- label: 中一足太阴脾经动脉（箕门）
  values: []
- label: 侯胃气配足阳明胃经动脉（冲阳）
  values: []
- label: 下一足少阴肾经动脉（太谿）
  values: []
