- label: 手太阴肺经
  values: []
- label: 手厥阴心包经
  values: []
- label: 手少阴心经
  values: []
- label: 手阳明大肠经
  values: []
- label: 手少阳三焦经
  values: []
- label: 手太阳小肠经
  values: []
- label: 足阳明胃经
  values: []
- label: 足少阳胆经
  values: []
- label: 足太阳膀胱经
  values: []
- label: 足太阴脾经
  values: []
- label: 足厥阴肝经
  values: []
- label: 足少阴肾经
  values: []
- label: 任脉
  values: []
- label: 督脉
  values: []
