- label: 大椎
  values: &1
  - 阴
  - 阳
  - 表
  - 里
  - 虚
  - 实
  - 寒
  - 热
- label: 陶道
  values: *1
- label: 身柱
  values: *1
- label: 神道
  values: *1
- label: 灵台
  values: *1
- label: 至阳
  values: *1
- label: 筋缩
  values: *1
- label: 中枢
  values: *1
- label: 脊中
  values: *1
- label: 命门
  values: *1
- label: 腰阳关
  values: *1
- label: 上髎
  values: *1
- label: 次髎
  values: *1
- label: 中髎
  values: *1
- label: 下髎
  values: *1
- label: 腰俞
  values: *1
- label: 长强
  values: *1
- label: 肩中俞
  values: *1
- label: 肩外俞
  values: *1
- label: 肩井
  values: *1
- label: 天臑
  values: *1
- label: 曲坦
  values: *1
- label: 秉风
  values: *1
- label: 天宗
  values: *1
- label: 臑俞
  values: *1
- label: 肩贞
  values: *1
- label: 附分
  values: *1
- label: 魄户
  values: *1
- label: 膏肓
  values: *1
- label: 神堂
  values: *1
- label: 意喜
  values: *1
- label: 隔关
  values: *1
- label: 魂门
  values: *1
- label: 阳纲
  values: *1
- label: 意舍
  values: *1
- label: 胃仓
  values: *1
- label: 盲门
  values: *1
- label: 志室
  values: *1
- label: 胞盲
  values: *1
- label: 大杼
  values: *1
- label: 风门
  values: *1
- label: 肺俞
  values: *1
- label: 厥阴俞
  values: *1
- label: 心俞
  values: *1
- label: 督俞
  values: *1
- label: 膈俞
  values: *1
- label: 肝俞
  values: *1
- label: 胆俞
  values: *1
- label: 脾俞
  values: *1
- label: 胃俞
  values: *1
- label: 三焦俞
  values: *1
- label: 肾俞
  values: *1
- label: 气海俞
  values: *1
- label: 大肠俞
  values: *1
- label: 关元俞
  values: *1
- label: 小肠俞
  values: *1
- label: 膀胱俞
  values: *1
- label: 中膂俞
  values: *1
- label: 白环俞
  values: *1
- label: 会阳
  values: *1
- label: 秩边
  values: *1
