- label: 左寸
  values: &1
  - 浮脉
  - 沉脉
  - 迟脉
  - 数脉
  - 滑脉
  - 涩脉
  - 虚脉
  - 实脉
  - 长脉
  - 短脉
  - 洪脉
  - 微脉
  - 细脉
  - 濡脉
  - 弱脉
  - 紧脉
  - 缓脉
  - 弦脉
  - 动脉
  - 促脉
  - 结脉
  - 代脉
  - 革脉
  - 牢脉
  - 散脉
  - 芤脉
  - 伏脉
  - 疾脉
- label: 左关
  values: *1
- label: 左尺
  values: *1
- label: 右寸
  values: *1
- label: 右关
  values: *1
- label: 右尺
  values: *1
