- lable: 舌色
  values:
    - 淡红舌
    - 淡白舌
    - 红舌
    - 绛舌
    - 紫舌
    - 淡紫舌
    - 紫红舌
    - 绛紫舌
    - 斑点舌
    - 青舌
    - 白苔
    - 薄白苔
    - 厚白苔
    - 黄苔
    - 灰苔
    - 黑苔
    - 灰黑苔
- lable: 舌苔
  values:
    - 薄苔
    - 后苔
    - 润苔
    - 燥苔
    - 滑苔
    - 糙苔
    - 腐苔
    - 腻苔
    - 光剥苔
    - 花剥苔
    - 地图苔
    - 全苔
    - 偏苔
    - 真苔
    - 假苔
- lable: 舌形
  values:
    - 老舌
    - 嫩舌
    - 胖大
    - 瘦薄
    - 芒刺
    - 裂纹
    - 齿痕
    - 光滑
- lable: 舌态
  values:
    - 痿软
    - 强硬
    - 歪斜
    - 颤动
    - 吐弄
    - 短缩
