- label: 脑区
  values: []
- label: 心区
  values: []
- label: 肺区
  values: []
- label: 胸乳区
  values: []
- label: 肝区
  values: []
- label: 胆区
  values: []
- label: 脾胃区
  values: []
- label: 生殖区
  values: []
- label: 肾区
  values: []
- label: 大肠/小肠区
  values: []
- label: 膀胱区
  values: []
